apiVersion: apps/v1
kind: Deployment
metadata:
  name:  spring-testapp
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  spring-testapp
  template:
    metadata:
      labels:
        app:  spring-testapp
    spec:
      containers:
        - name:  spring-testapp
          image: giddy87/springboot:app-462d32d3adcb05db40ef7a3464c32f7d58beb46d
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
         
      
