apiVersion: v1
kind: Service
metadata:
  name:  spring-testapp
  namespace: default
spec:
  selector:
    app: spring-testapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
