apiVersion: v1
kind: Service
metadata:
  name: springmysql
  namespace: default
spec:
  selector:
    app: springmysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
